package hudson.plugins.promoted_builds.integrations.jobdsl;

import groovy.util.Node;
import hudson.plugins.promoted_builds.conditions.ManualCondition;

import java.util.Collection;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Special holder for the ManualCondition generated by the Job DSL Plugin
 * 
 * @author Dennis Schulte
 */
@XStreamAlias("hudson.plugins.promoted_builds.conditions.ManualCondition")
public class JobDslManualCondition extends ManualCondition {

    private Collection<Node> parameterDefinitionNodes;

    public Collection<Node> getParameterDefinitionNodes() {
        return parameterDefinitionNodes;
    }

    public void setParameterDefinitionNodes(Collection<Node> parameterDefinitionNodes) {
        this.parameterDefinitionNodes = parameterDefinitionNodes;
    }

}
