package hudson.plugins.promoted_builds.integrations.jobdsl;

import hudson.plugins.promoted_builds.PromotionCondition;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Special holder for the ReleasePromotionCondition generated by the Job DSL Plugin
 * 
 * @author Dennis Schulte
 */
@XStreamAlias("hudson.plugins.release.promotion.ReleasePromotionCondition")
public class ReleasePromotionCondition extends PromotionCondition {

}
