package hudson.plugins.promoted_builds.integrations.jobdsl;

import hudson.plugins.promoted_builds.PromotionCondition;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Special holder for the ReleasePromotionCondition generated by the Job DSL Plugin
 * 
 * @author Dennis Schulte
 * @deprecated Should be avoided in favor of Automatically Generated DSL. Relying on name collision does not scale
 *  well.
 */
@XStreamAlias("hudson.plugins.release.promotion.ReleasePromotionCondition")
@Deprecated
public class ReleasePromotionCondition extends PromotionCondition {

}
